/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import crud.Apoio_logisticoCRUD;
import crud.Aval_cursoCRUD;
import crud.Aval_eventoCRUD;
import crud.Tema_cursoCRUD;
import entity.Apoio_logistico;
import entity.Aval_curso;
import entity.Aval_evento;
import entity.Tema_curso;
import static gui.Principal.e;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import util.ModelTApoioLog;
import util.ModelTAvalCurso;
import util.ModelTAvalEvento;

/**
 *
 * @author jhonatan
 */
public class AbrirEvento extends javax.swing.JFrame {

    /**
     * Creates new form AbrirEvento
     */
    private AbrirEvento() {
        initComponents();
    }

    private static AbrirEvento ae;

    public static synchronized AbrirEvento getInstance() {
        if (ae == null) {
            ae = new AbrirEvento();
        }
        return ae;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Título");

        jLabel2.setText("Data Final");

        jLabel3.setText("Data Inicial");

        jLabel4.setText("Local");

        jLabel5.setText("Id");

        jTextField3.setEnabled(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Título"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Editar aula");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Deletar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Avaliar evento");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Apoio logístico");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Inserir aula");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Avaliar aulas");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jButton2)
                .addGap(77, 77, 77)
                .addComponent(jButton4)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(21, 21, 21)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        editarAula();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        abrirAvalEvento = AbrirAvalEvento.getInstance();
        preencherTbAvalEvento();
        abrirAvalEvento.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        abrirApoioLog = AbrirApoioLog.getInstance();
        preencherTbApoioLog();
        abrirApoioLog.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        e.setTitulo(jTextField1.getText());
        e.setDataI(new java.sql.Date(jDateChooser1.getDate().getTime()));
        e.setDataF(new java.sql.Date(jDateChooser2.getDate().getTime()));
        e.setLocal(jTextField2.getText());

        if (e.getTitulo().equals("") || e.getDataI().equals("")
                || e.getDataF().equals("") || e.getLocal().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher todos os campos");
        } else if (Principal.crud.editar(Principal.e)) {
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
            this.dispose();
            Principal.preencherTab();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao salvar");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        tc = new Tema_curso();
        tc.setTitulo(JOptionPane.showInputDialog("Inserir o tema"));
        tc.setEvento_id(Principal.e.getId());
        if (tc.getTitulo() != null) {
            if (tcCrud.inserir(tc)) {
                JOptionPane.showMessageDialog(null, "Inserido com sucesso!");
                Principal.preencherTabTC(tc.getEvento_id());
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao inserir");
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            editarAula();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        abrirCurso = AbrirCurso.getInstance();
        String[] a = new String[Principal.listaTc.size()];
        if (a.length == 0) {
            JOptionPane.showMessageDialog(null, "O evento não possui aulas cadastradas");
        } else {
            for (int i = 0; i < Principal.listaTc.size(); i++) {
                a[i] = Principal.listaTc.get(i).getTitulo();
            }
            preencherTbCursos();
            abrirCurso.setVisible(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int rowIndex = jTable1.getSelectedRow();

        if (rowIndex != -1) {
            tc = Principal.mttc.get(rowIndex);
            int jop = JOptionPane.showConfirmDialog(null, "Confirma a exclusão?");
            if (jop == JOptionPane.YES_OPTION) {
                if (tcCrud.deletar(tc)) {
                    JOptionPane.showMessageDialog(null, "Excluido com sucesso");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao excluir");
                }
                Principal.preencherTabTC(Principal.e.getId());
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    public void editarAula() {

        int rowIndex = jTable1.getSelectedRow();

        if (rowIndex != -1) {
            tc = Principal.mttc.get(rowIndex);
            tc.setTitulo(JOptionPane.showInputDialog("Insira o novo título"));
            tc.setEvento_id(Principal.e.getId());

            if (tc.getTitulo() != null) {
                if (tcCrud.editar(tc)) {
                    JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao salvar");
                }
            }

            Principal.preencherTabTC(tc.getEvento_id());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbrirEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbrirEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbrirEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbrirEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbrirEvento().setVisible(true);
            }
        });
    }

    public static void preencherTbCursos() {
        listaAc = crud.obterTodos(Principal.e.getId());
        mtac = new ModelTAvalCurso(listaAc);
        abrirCurso.jTable1.setModel(mtac);
        abrirCurso.jTable1.getTableHeader().setReorderingAllowed(false);
        abrirCurso.jTable1.setAutoResizeMode(abrirCurso.jTable1.AUTO_RESIZE_ALL_COLUMNS);
        abrirCurso.jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public static void preencherTbAvalEvento() {
        listaAe = aeCrud.obterTodos(Principal.e.getId());
        mtae = new ModelTAvalEvento(listaAe);
        abrirAvalEvento.jTable1.setModel(mtae);
        abrirAvalEvento.jTable1.getTableHeader().setReorderingAllowed(false);
        abrirAvalEvento.jTable1.setAutoResizeMode(abrirAvalEvento.jTable1.AUTO_RESIZE_ALL_COLUMNS);
        abrirAvalEvento.jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public static void preencherTbApoioLog() {
        listaAl = alCrud.obterTodos(Principal.e.getId());
        mtal = new ModelTApoioLog(listaAl);
        abrirApoioLog.jTable1.setModel(mtal);
        abrirApoioLog.jTable1.getTableHeader().setReorderingAllowed(false);
        abrirApoioLog.jTable1.setAutoResizeMode(abrirApoioLog.jTable1.AUTO_RESIZE_ALL_COLUMNS);
        abrirApoioLog.jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    protected static com.toedter.calendar.JDateChooser jDateChooser1;
    protected static com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    protected static javax.swing.JTable jTable1;
    protected static javax.swing.JTextField jTextField1;
    protected static javax.swing.JTextField jTextField2;
    protected static javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
    protected static ArrayList<Aval_curso> listaAc = new ArrayList<>();
    protected static ArrayList<Aval_evento> listaAe = new ArrayList<>();
    protected static ArrayList<Apoio_logistico> listaAl = new ArrayList<>();
    protected static final Aval_cursoCRUD crud = new Aval_cursoCRUD();
    protected static ModelTAvalCurso mtac;
    private static AbrirCurso abrirCurso;
    protected static Aval_curso ac = new Aval_curso();
    private static Tema_curso tc;
    protected static final Tema_cursoCRUD tcCrud = new Tema_cursoCRUD();
    private static AbrirAvalEvento abrirAvalEvento;
    protected static Aval_evento avE;
    protected static final Aval_eventoCRUD aeCrud = new Aval_eventoCRUD();
    private static AbrirApoioLog abrirApoioLog;
    protected static final Apoio_logisticoCRUD alCrud = new Apoio_logisticoCRUD();
    protected static Apoio_logistico al;
    protected static ModelTAvalEvento mtae;
    protected static ModelTApoioLog mtal;
}
